#!/bin/sh
# Script to install modules and continue running server forever

# Move to folder if not already
cd "$(dirname $0)"

[ -d node_modules ] || npm i

git fetch
A="$(git status -sb)"
echo "$A" | grep 'behind ' > /dev/null
if [ $? -eq 0 ]; then
echo "$A" | grep 'ahead \| [A-Z] ' > /dev/null
if [ $? -eq 0 ]; then
echo "\033[33mYour server is not up to date.\012As it has been modified, consider updating it with a git rebase\012Press enter to start the server, or CTRL+C to exit\033[m"
else
git pull
node -e "console.log('\\x1b[32mServer has been updated to '+require('./package.json').version+'.\\nPress enter to continue')"
fi; read A; fi
A=

while true; do
node . && break
echo "\012\033[31mServer crashed (exit code $?)"
done