#!/bin/sh
# Script to install modules and continue running server forever

# Move to folder if not already
cd "${0%/*}"

git fetch
$A=$(git status)
echo "$A" | grep "Your branch is up to date with '" &> /dev/null
if [ $? -neq 0 ]; then
echo "$A" | grep 'nothing to commit' &> /dev/null
if [ $? -eq 0 ]; then
git pull
node -e "console.log('\\x1b[33mUpdated server to '+require('./package.json').version)"
else
echo "\033[33mYour server is not up to date. As it has been modified, consider updating it with a git rebase\012Press enter to start the server, or CTRL+C to exit\033[m"
read A
fi; fi
A=

[ -d node_modules ] || npm i

while true; do
node . && break
echo "\012\033[31mServer crashed (exit code $?)"
sleep 1
done