import './building/glass.js'
import './building/planks.js'
import './building/torch.js'
import './building/wool.js'

import './misc/containers.js'
import './misc/destructive.js'
import './misc/dragon_egg.js'
import './misc/minerals.js'
import './misc/portals.js'

import './natural/air.js'
import './natural/crops.js'
import './natural/end.js'
import './natural/grass.js'
import './natural/ice.js'
import './natural/leaves.js'
import './natural/logs.js'
import './natural/nether.js'
import './natural/ores.js'
import './natural/sand.js'
import './natural/sandstone.js'
import './natural/saplings.js'
import './natural/snow.js'
import './natural/stone.js'
import './natural/water.js'

import './technical/commandblock.js'
import './technical/functional.js'
import './technical/indestructible.js'