#!/bin/sh
# Script to install modules and continue running server forever

# Move to folder if not already
cd "$(dirname $0)"

runtime="node --allow-natives-syntax ."
update="npm i"
# command -v deno && runtime="deno run --reload -A index.js"
# command -v bun && runtime="bun ."

[ -d node_modules ] || npm i

git fetch
A="$(git status -sb)"
FLAGS=
echo "$A" | grep 'behind ' > /dev/null
if [ $? -eq 0 ]; then
echo "$A" | grep 'ahead \| [A-Z] ' > /dev/null
if [ $? -eq 0 ]; then
echo "\033[33mYour server is not up to date.\012As it has been modified, consider updating it with a git rebase\012Press enter to start the server, or CTRL+C to exit\033[m"
else
git pull
node -e "console.log('Server has been updated to '+require('./package.json').version+'\\n\\n')"
fi; FLAGS=" -manual"; fi
A=

while true; do
$runtime $FLAGS "$@" && break
FLAGS=
echo "\012\033[31mServer crashed (exit code $?)"
sleep 2
done